/**
 * Automated Timetable Sync using Antigravity CLI (agy)
 * Inspects TT.jpeg and updates timetable.json & timetable.js
 */
const { exec } = require('child_process');
const fs = require('fs');
const path = require('path');

const DIR = __dirname;
function getTimetableImage() {
  const candidates = ['TT.jpeg', 'TT.jpg', 'TT.png', 'TT1.jpeg'];
  for (const name of candidates) {
    const full = path.join(DIR, name);
    if (fs.existsSync(full)) return { filename: name, path: full };
  }
  return null;
}

const TT_JSON = path.join(DIR, 'timetable.json');
const TT_JS = path.join(DIR, 'timetable.js');

function runSync() {
  return new Promise((resolve, reject) => {
    const imgInfo = getTimetableImage();
    if (!imgInfo) {
      return reject(new Error('Timetable image (TT.jpeg, TT.jpg, or TT.png) not found in ' + DIR));
    }

    console.log(`[AGY Sync] Analyzing ${imgInfo.filename} with agy...`);
    const prompt = `Inspect the image file ${imgInfo.filename} in the current folder. Extract all timetable slots and write them as valid JSON into timetable.json. Keys must be Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday. Each day is an array of objects: { "start": "HH:MM", "end": "HH:MM", "subject": "Name", "teacher": "Code/Name", "type": "theory" | "lab" | "break" }. Do not add markdown backticks to timetable.json, write raw JSON only.`;

    exec(`agy -p "${prompt}" --dangerously-skip-permissions`, { cwd: DIR }, (error, stdout, stderr) => {
      if (error) {
        console.error('[AGY Sync Error]:', error.message);
        return reject(error);
      }

      console.log('[AGY Output]:', stdout);

      // Verify timetable.json was generated or updated
      if (fs.existsSync(TT_JSON)) {
        try {
          const raw = fs.readFileSync(TT_JSON, 'utf8');
          // Strip any potential markdown code blocks if agy included them
          const cleaned = raw.replace(/^```json\s*/i, '').replace(/\s*```$/, '').trim();
          const parsed = JSON.parse(cleaned);

          // Write cleaned JSON
          fs.writeFileSync(TT_JSON, JSON.stringify(parsed, null, 2), 'utf8');

          // Write timetable.js for standalone file:// protocol support
          const jsContent = `// Auto-generated by AGY from TT.jpeg\nwindow.TIMETABLE_CACHE = ${JSON.stringify(parsed, null, 2)};\n`;
          fs.writeFileSync(TT_JS, jsContent, 'utf8');

          console.log('[AGY Sync] Success! Updated timetable.json and timetable.js');
          return resolve(parsed);
        } catch (parseErr) {
          console.error('[AGY Sync] JSON Parse error:', parseErr.message);
          return reject(parseErr);
        }
      } else {
        return reject(new Error('timetable.json was not created by agy'));
      }
    });
  });
}

if (require.main === module) {
  runSync()
    .then(() => {
      console.log('[AGY Sync] Completed successfully.');
      process.exit(0);
    })
    .catch((err) => {
      console.error('[AGY Sync] Failed:', err);
      process.exit(1);
    });
}

module.exports = { runSync };
